name: Run tests

on:
  push:
  pull_request:
    branches:
      - master
      - develop

jobs:
  build:
    name: Test and Build
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.13.x
        uses: actions/setup-go@v1
        with:
          go-version: "1.13.x"

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Checkout project
        uses: actions/checkout@v1

      - name: Install NPM deps
        run: yarn install

      - name: Enforce Javascript lints
        run: yarn run lint

      - name: Test and Build Javascript
        run: yarn run build:prod

      - name: Download go-bindata tool
        run: env GO111MODULE=off go get -u -v github.com/go-bindata/go-bindata/...

      - name: Test and Build Server
        run: env PATH="$HOME/go/bin:$PATH" make bindata test build
